### ISSUE TITLE
Power BI couldn't work with IRIS CE

### ISSUE THREAD

**Issue by xedinseu** [teccod/Logi-Atscale-Tableau-Issues#32]
When we try to update the tables in Power BI the process is fine until the start of the 5th table update. We get an Access Deny error. Checking IRIS, we see that it was not possible to allocate a license for user _system. The reason for this may be that to update each table, Power BI creates a separate connection and exceeds the limit of 5 licenses of the CE version of IRIS.

**Comment by jakcpto** [comment]
Having setting in AtScale Server to limit number of concurrent connections to 4 solved this issue.
